# This will show the time on a 2nd line
# Add a "\" at the end of an item, if you want the next item to show on the same line
format = """
$username\
$hostname\
$time\
$all\
$directory
$kubernetes
$character
"""

[character]
success_symbol = '[❯❯❯❯](#487ef0 bold)'
error_symbol = '[XXXX](#f34d4f bold)'
vicmd_symbol = '[❮❮❮❮](#04d1f9 bold)'

[battery]
disabled = true

[gcloud]
disabled = true

[time]
style = '#04d1f9 bold'
disabled = false
format = '[\[$time\]]($style) '
# https://docs.rs/chrono/0.4.7/chrono/format/strftime/index.html
# %T	00:34:60	Hour-minute-second format. Same to %H:%M:%S.
# time_format = '%y/%m/%d %T'
time_format = '%y/%m/%d'

# For this to show up correctly, you need to have cluster access
# So your ~/.kube/config needs to be configured on the local machine
[kubernetes]
disabled = false
# context = user@cluster
# format = '[$user@$cluster \($namespace\)](#f34d4f) '
# format = '[$cluster \($namespace\)](#f34d4f) '
# Apply separate colors for cluster and namespace
format = '[$cluster](#f34d4f bold) [$namespace](#487ef0 bold) '
# format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
# Only dirs that have this file inside will show the kubernetes prompt
# detect_files = ['900-detectkubernetes.sh']
# detect_env_vars = ['STAR_USE_KUBE']
# contexts = [
#   { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "💔 " },
# ]

[username]
style_user = '#04d1f9 bold'
style_root = 'white bold'
format = '[$user]($style).@.'
show_always = true

[hostname]
ssh_only = true
format = '(white bold)[$hostname](#487ef0 bold)'

[directory]
style = '#90b1f6 bold'
truncation_length = 0
truncate_to_repo = false

[ruby]
detect_variables = []
detect_files = ['Gemfile', '.ruby-version']
