# Filename: ~/.prettierrc.yaml

# Default configuration applied to all files
# proseWrap: "preserve"

# You might not want proseWrap to affect YAML files, so it's not set at the top level here
# https://prettier.io/docs/en/configuration#configuration-overrides
overrides:
  # Specific override for Markdown (.md) files
  - files: "*.md"
    options:
      proseWrap: "always"
  # # Specific override for Markdown (.md) files in a specific directory
  # - files:
  #     - "050-personal/work/doc/goto/monitoring/projects/**/*.md"
  #   options:
  #     # tabWidth: 4
  #     # tab_width: 4
  #     # indent_style: "space"
  #     # indent_size: 5
  #     proseWrap: "always"
