# Filename: ~/github/dotfiles-latest/neovim/nvim-lazyvim/.markdownlint.yaml
# ~/github/dotfiles-latest/neovim/nvim-lazyvim/.markdownlint.yaml

# Hard tabs
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md010.md
MD010:
  code_blocks: false

# Line length
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
MD013:
  code_blocks: false
  headings: false
  tables: false

# Inline HTML
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md033.md
MD033:
  false
  # allowed_elements: ["a", "img", "div"]

# Unordered list indentation
# I disable this because for some documents I use 4 space indenting, like
# markdown files that I need to upload to confluence
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md007.md
MD007: false
